### ISSUE TITLE
Definir casos de Uso

### ISSUE THREAD

**Issue by lual2** [Pandemials/Pandemials#10]
Como Pandemials
Quiero crear los casos de uso
para hacer los diagramas de los casos de uso

**Comment by johssymiranda** [comment]
![UML 1](https://user-images.githubusercontent.com/49239482/81008535-196f2200-8e21-11ea-838d-a86bd16f3d98.jpg)
![UML 2](https://user-images.githubusercontent.com/49239482/81008566-24c24d80-8e21-11ea-82a6-4217915a7426.jpg)
![UML 3](https://user-images.githubusercontent.com/49239482/81008569-255ae400-8e21-11ea-901e-7a3ae334fe00.jpg)
![UML 4-modificar](https://user-images.githubusercontent.com/49239482/81191072-95cf4580-8f86-11ea-8e3b-c69d923d8a5c.jpg)
![UML 5-eliminar](https://user-images.githubusercontent.com/49239482/81191074-97007280-8f86-11ea-84ec-127338470117.jpg)

**Comment by johssymiranda** [comment]
Aumentar los diagramas faltantes

**Comment by johssymiranda** [comment]
![UML1-Inicio](https://user-images.githubusercontent.com/49239482/81130371-88c63e00-8f15-11ea-997a-e0a380048c79.jpg)
![UML2-Grupos de Trabajo](https://user-images.githubusercontent.com/49239482/81198338-5c4f0800-8f8f-11ea-8bf2-8b804dc1f710.jpg)
![UML3-Biblioteca](https://user-images.githubusercontent.com/49239482/81189518-a4b4f880-8f84-11ea-9dc9-858be387c8eb.jpg)
