### ISSUE TITLE
Implementacion de casos de uso

### ISSUE THREAD

**Issue by lual2** [Pandemials/Pandemials#16]
Como Pandemials
quiero desarrollar los distintos casos de uso
para poder entender mejor la funcionalidad del proyecto

**Comment by johssymiranda** [comment]
![UML 1](https://user-images.githubusercontent.com/49239482/80927735-cbe5ad00-8d6d-11ea-8d91-4d9dd0471727.jpg)
![UML 2](https://user-images.githubusercontent.com/49239482/80927736-cd16da00-8d6d-11ea-889d-e799e515b066.jpg)
![UML 3](https://user-images.githubusercontent.com/49239482/80927737-cdaf7080-8d6d-11ea-9efa-1a601dbcc28b.jpg)

**Comment by johssymiranda** [comment]
Después del diseño de los diagramas de casos de uso por cada pantalla empezar a programar

**Comment by johssymiranda** [comment]
ver si necesitaremos la ayuda de otras librerías o programas

**Comment by lual2** [comment]
Se editara algunos cambios en los casos de uso
