### ISSUE TITLE
Diagrama orientado a objetos

### ISSUE THREAD

**Issue by johssymiranda** [Pandemials/Pandemials#17]
Como Pandemials
Queremos diseñar el diagrama 
Para poder tener un orden

**Comment by lual2** [comment]
![Untitled Document - Copy (3)](https://user-images.githubusercontent.com/38512304/82442795-5288d280-9a6e-11ea-8de0-8dd86bfa66a9.png)

**Comment by lual2** [comment]
Se consulto las dudas y se pudo mejorar el diagrama
