### ISSUE TITLE
Buscar proyectos en SICOES

### ISSUE THREAD

**Issue by johssymiranda** [Pandemials/Pandemials#2]
Como Pandemials 
queremos buscar un proyecto
 para desarrollarlo y poner tener una buena organización

**Comment by lual2** [comment]
Se encontró varios proyectos, se hizo una selección teniendo como finalistas
tres proyectos.

**Comment by johssymiranda** [comment]
Verificar si los proyectos seleccionados cumplan con los requerimientos de la materia y ver su alcance
