### ISSUE TITLE
Diagramas de Secuencia

### ISSUE THREAD

**Issue by johssymiranda** [Pandemials/Pandemials#20]
Como Pandemials 
Queremos tener un diagrama de secuencia
para poder orientarnos mejor

**Comment by lual2** [comment]
Diagrama secuencia cliente
![DiagramaSec](https://user-images.githubusercontent.com/38512304/82421831-a6d08a00-9a4f-11ea-90a3-798734f329b9.png)

**Comment by lual2** [comment]
Diagrama de Secuencia Administrador
![Untitled Document - Copy](https://user-images.githubusercontent.com/38512304/82423519-d7b1be80-9a51-11ea-8acb-a455b839f6db.png)

**Comment by lual2** [comment]
Diagrama de Secuencia Editor
![Untitled Document - Copy - Copy](https://user-images.githubusercontent.com/38512304/82424877-c79ade80-9a53-11ea-83fa-c9f741980dee.png)
