### ISSUE TITLE
Ceremonias de Scrum

### ISSUE THREAD

**Issue by johssymiranda** [Pandemials/Pandemials#30]
Como Pandemials
Queremos Cumplimiento del objetivo
Para Ver si vamos por el camino correcto

**Comment by lual2** [comment]
Cada día se realizo las  ceremonias de scrum, para ver el avance y resolver dudas

**Comment by johssymiranda** [comment]
La próxima semana se realiza las c ultimas ceremonias para ver los avances y bloqueos
