### ISSUE TITLE
Resumen Sprint 3, Sprint 4

### ISSUE THREAD

**Issue by johssymiranda** [Pandemials/Pandemials#32]
Como Panemials
Queremos realizar el resumen
Para poder tener el wiki organizado

**Comment by johssymiranda** [comment]
![diag base de datos](https://user-images.githubusercontent.com/49239482/82667149-3d927780-9c05-11ea-9de1-2db5f81c5db8.jpg)

**Comment by lual2** [comment]
Resumen concreto del sprint 3 y 4
