### ISSUE TITLE
Realizar la descripción del proyecto

### ISSUE THREAD

**Issue by johssymiranda** [Pandemials/Pandemials#5]
como pandemials
queremos tener la visión, misión y Objetivos del proyecto
para tener un avance del documento

**Comment by johssymiranda** [comment]
Aumentar la Descripcion del cliente

**Comment by johssymiranda** [comment]
Borrar el titulo del Objetivo del proyecto

**Comment by lual2** [comment]
Definir los objetivos específicos o institucionales
