### ISSUE TITLE
Desarrollar diseños de mockup

### ISSUE THREAD

**Issue by johssymiranda** [Pandemials/Pandemials#7]
Como Pandemials
Queremos desarrollar los diseños del mockups
Para poder realizar los casos de uso para el proyecto

**Comment by lual2** [comment]
![Pandemials2-10](https://user-images.githubusercontent.com/38512304/81233034-00eb3d00-8fc4-11ea-9eec-cc6e3e0b64d1.png)

![Mockup1 1-Trabajo de grado](https://user-images.githubusercontent.com/49239482/81209223-3c731080-8f9e-11ea-978d-e6c6bb49c75c.jpg)
![Mockup2-BIBLIOTECA](https://user-images.githubusercontent.com/49239482/81185285-66690a80-8f7f-11ea-8ec0-b5681487ccfa.jpg)
![Mockup3-Login web](https://user-images.githubusercontent.com/49239482/81210792-688f9100-8fa0-11ea-970f-33751e25e6c3.jpg)
![Mockup4-Actualizar](https://user-images.githubusercontent.com/49239482/81185297-6832ce00-8f7f-11ea-91af-8e4456d30d8d.jpg)
![Mockup5-añadir o elmminar](https://user-images.githubusercontent.com/49239482/81185299-68cb6480-8f7f-11ea-9213-9550d676426c.jpg)
![Mockup6-sing in](https://user-images.githubusercontent.com/49239482/81185303-6963fb00-8f7f-11ea-9722-fae3f23b6bf3.jpg)

**Comment by johssymiranda** [comment]
Realizar los cambios consultados con el docente

**Comment by johssymiranda** [comment]
Tener mas diseños que casos se uso de lo contrario baja la nota
