### ISSUE TITLE
Definir la herramienta a usar para Mockup

### ISSUE THREAD

**Issue by johssymiranda** [Pandemials/Pandemials#8]
Como Pandemials
Queremos definir la herramienta
para tener un diseño a seguir

**Comment by lual2** [comment]
Se definió la herramienta, se usara IIlustrator.

**Comment by johssymiranda** [comment]
Preguntar si el ingreso a "Usuario" se pondrá con un URL o con un boton

**Comment by johssymiranda** [comment]
Cambiar "Contacto" por solo las redes sociales en la parte superior de la pagina.
